config/routes.rb
Rails.application.routes.draw do

  root to: redirect("admin/services")

  resources :passwords, controller: "clearance/passwords", only: [:create]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"

  constraints Clearance::Constraints::SignedIn.new do
    root to: redirect("admin/services"), as: :signed_in_root
  end

  namespace :admin do
    resources :services
    resources :tags

    root to: redirect("admin/services")
  end

  namespace :api do
    namespace :v1 do
      resources :tags do
        member do
          get "services"
          get "subtags"
        end
      end

      resources :services do
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :service
  belongs_to :tag
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :categorizations, :dependent => :destroy
  has_many :tags, :through => :categorizations

  def full_street_address
    [address, administrative_area, city, zip].compact.join(', ')
  end

  geocoded_by :full_street_address

  after_validation :geocode
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :categorizations, :dependent => :destroy
  has_many :services, :through => :categorizations
  belongs_to :parent, class_name: "Tag", optional: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Clearance::Controller
    before_action :require_login
  end
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Service.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Service.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Tag.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Tag.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/services_controller.rb
class Api::V1::ServicesController < ApplicationController
  # GET /services?lat=0.0&lng=0.0
  def index
    lat = params[:lat].to_f
    lng = params[:lng].to_f
    @non_geocoded_services = Service.not_geocoded
    @geocoded_services = Service.near([lat, lng], 30)
    render json: (@non_geocoded_services + @geocoded_services), lat: lat, lng: lng
  end

  # GET /services/:id
  def show
    @service = Service.find(params[:id])
    render json: @service
  end
end

app/controllers/api/v1/tags_controller.rb
class Api::V1::TagsController < ApplicationController
  # GET /api/v1/tags
  def index
    @tags = Tag.where("parent_id IS ?", nil)
    render json: @tags
  end

  # GET /api/v1/tags/:id
  def show
    @tag = Tag.find(params[:id])
    render json: @tag
  end

  # GET /api/v1/tags/:id/subtags
  def subtags
    parent = params[:id]
    @tags = Tag.where(parent_id: parent)
    render json: @tags
  end

  # GET /api/v1/tags/:id/services?lat=0.0&lng=0.0
  def services
    @tag = Tag.find(params[:id])
    lat = params[:lat].to_f
    lng = params[:lng].to_f
    @non_geocoded_services = @tag.services.not_geocoded
    @geocoded_services = @tag.services.near([lat, lng], 30)
    render json: (@non_geocoded_services + @geocoded_services), lat: lat, lng: lng
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/admin/application/_sidebar.html.erb
<%#
# Sidebar

This partial is used to display the sidebar in Administrate.
By default, the sidebar contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<ul class="sidebar__list">
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <li>
      <%= link_to(
        display_resource_name(resource),
        [namespace, resource],
        class: "sidebar__link sidebar__link--#{nav_link_state(resource)}"
      ) %>
    </li>
  <% end %>
</ul>

app/views/layouts/admin/application.html.erb
<%#
# Application Layout

This view template is used as the layout
for every page that Administrate generates.

By default, it renders:
- Sidebar for navigation
- Content for a search bar
  (if provided by a `content_for` block in a nested page)
- Flashes
- Links to stylesheets and Javascripts
%>

<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= content_for(:title) %> | <%= Rails.application.class.parent_name.titlecase %></title>
  <%= render "stylesheet" %>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="header">
    <% if signed_in? %>
      <%= button_to "Sign out", sign_out_path, method: :delete %>
      <span><%= current_user.email %></span>
    <% else %>
      <%= link_to "Sign in", sign_in_path %>
    <% end %>
  </div>
  <div class="app-container">
    <div class="sidebar">
      <%= render "sidebar" -%>
    </div>

    <main class="main-content" role="main">
      <%= content_for(:search) %>
      <%= render "flashes" -%>
      <%= yield %>
    </main>

  </div>

  <%= render "javascript" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>